### ISSUE TITLE
Straditize fails to launch

### ISSUE THREAD

**Issue by olijw** [Chilipp/straditize#19]
Hi,

A lot like Brian in Issue #17, I'd love to use Straditize in my research but haven't been able to launch it successfully, despite trying on three separate computers now. I've followed the installation instructions on your website and also tried the solution that resolved #17, but I get similar errors each time. Running...

conda install -n base -c defaults --override-channels anaconda-client
conda env create -n straditize chilipp/straditize-env
conda activate straditize

...all works fine (as does the standard installation of just the latter two lines), but when I type...

straditize

...I get the following:

<details>
(straditize) C:\Users\olijw>straditize
Traceback (most recent call last):
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\Scripts\straditize-script.py", line 6, in <module>
    from straditize.__main__ import main
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\straditize\__main__.py", line 21, in <module>
    from psyplot_gui import docstrings
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot_gui\__init__.py", line 15, in <module>
    import psyplot
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot\__init__.py", line 7, in <module>
    from psyplot.config.rcsetup import rcParams
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot\config\__init__.py", line 13, in <module>
    from .rcsetup import psyplot_fname
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot\config\rcsetup.py", line 25, in <module>
    @docstrings.get_sectionsf('safe_list')
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\docrep\decorators.py", line 110, in deprecated
    return func(self, *args, **kwargs)
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\docrep\__init__.py", line 927, in get_sectionsf
    return self.get_sections(base=args[0], *args[1:], **kwargs)
TypeError: get_sections() missing 1 required positional argument: 's'

</details>

This same error text ("TypeError: get_sections() missing 1 required positional argument: 's'") has come up most times I've tried to launch Straditize now, and I'm not sure how to fix it. Any help you can give would be very gratefully received!

Thanks,

Oli

ps, while this is certainly annoying, it doesn't feel like the weirdest error message I've had trying to use Straditize: my old laptop (Windows 8.1) would give me a pop-up error window saying "This Windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586 or above)." Quite why Bluetooth was involved I have no idea..!

Additional information on this problem:

#### Environment information

<details>
<summary>
(straditize) C:\Users\olijw>psyplot -aV
Traceback (most recent call last):
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\Scripts\psyplot-script.py", line 6, in <module>
    from psyplot.__main__ import main
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot\__init__.py", line 7, in <module>
    from psyplot.config.rcsetup import rcParams
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot\config\__init__.py", line 13, in <module>
    from .rcsetup import psyplot_fname
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot\config\rcsetup.py", line 25, in <module>
    @docstrings.get_sectionsf('safe_list')
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\docrep\decorators.py", line 110, in deprecated
    return func(self, *args, **kwargs)
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\docrep\__init__.py", line 927, in get_sectionsf
    return self.get_sections(base=args[0], *args[1:], **kwargs)
TypeError: get_sections() missing 1 required positional argument: 's'
</summary>
</details>

<details>
<summary>
(straditize) C:\Users\olijw>straditize -V
Traceback (most recent call last):
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\Scripts\straditize-script.py", line 6, in <module>
    from straditize.__main__ import main
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\straditize\__main__.py", line 21, in <module>
    from psyplot_gui import docstrings
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot_gui\__init__.py", line 15, in <module>
    import psyplot
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot\__init__.py", line 7, in <module>
    from psyplot.config.rcsetup import rcParams
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot\config\__init__.py", line 13, in <module>
    from .rcsetup import psyplot_fname
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\psyplot\config\rcsetup.py", line 25, in <module>
    @docstrings.get_sectionsf('safe_list')
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\docrep\decorators.py", line 110, in deprecated
    return func(self, *args, **kwargs)
  File "C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\lib\site-packages\docrep\__init__.py", line 927, in get_sectionsf
    return self.get_sections(base=args[0], *args[1:], **kwargs)
TypeError: get_sections() missing 1 required positional argument: 's'
</summary>
</details>

<details>
<summary>
(straditize) C:\Users\olijw>conda info -a

     active environment : C:\Users\olijw\miniconda3\envs\straditize\envs\straditize
    active env location : C:\Users\olijw\miniconda3\envs\straditize\envs\straditize
            shell level : 3
       user config file : C:\Users\olijw\.condarc
 populated config files :
          conda version : 4.8.4
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\olijw\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\olijw\miniconda3\pkgs
                          C:\Users\olijw\.conda\pkgs
                          C:\Users\olijw\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\olijw\miniconda3\envs
                          C:\Users\olijw\.conda\envs
                          C:\Users\olijw\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.23.0 CPython/3.8.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

# conda environments:
#
base                     C:\Users\olijw\miniconda3
straditize               C:\Users\olijw\miniconda3\envs\straditize
                      *  C:\Users\olijw\miniconda3\envs\straditize\envs\straditize

sys.version: 3.8.3 (default, May 19 2020, 06:50:17) [...
sys.prefix: C:\Users\olijw\miniconda3
sys.executable: C:\Users\olijw\miniconda3\python.exe
conda location: C:\Users\olijw\miniconda3\lib\site-packages\conda
conda-build: None
conda-env: C:\Users\olijw\miniconda3\Scripts\conda-env.exe
conda-server: C:\Users\olijw\miniconda3\Scripts\conda-server.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: straditize
CONDA_EXE: C:\Users\olijw\miniconda3\condabin\..\Scripts\conda.exe
CONDA_EXES: "C:\Users\olijw\miniconda3\condabin\..\Scripts\conda.exe"
CONDA_PREFIX: C:\Users\olijw\miniconda3\envs\straditize\envs\straditize
CONDA_PREFIX_1: C:\Users\olijw\miniconda3
CONDA_PREFIX_2: C:\Users\olijw\miniconda3\envs\straditize
CONDA_PROMPT_MODIFIER: (straditize)
CONDA_PYTHON_EXE: C:\Users\olijw\miniconda3\envs\straditize\python.exe
CONDA_ROOT: C:\Users\olijw\miniconda3
CONDA_SHLVL: 3
CURL_CA_BUNDLE: <not set>
HOMEPATH: \Users\olijw
PATH: C:\Users\olijw\miniconda3;C:\Users\olijw\miniconda3\Library\mingw-w64\bin;C:\Users\olijw\miniconda3\Library\usr\bin;C:\Users\olijw\miniconda3\Library\bin;C:\Users\olijw\miniconda3\Scripts;C:\Users\olijw\miniconda3\bin;C:\Users\olijw\miniconda3\envs\straditize\envs\straditize;C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\Library\mingw-w64\bin;C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\Library\usr\bin;C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\Library\bin;C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\Scripts;C:\Users\olijw\miniconda3\envs\straditize\envs\straditize\bin;C:\Users\olijw\miniconda3\condabin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\olijw\AppData\Local\Microsoft\WindowsApps;.
PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
</summary>
</details>

<details>
<summary>
(straditize) C:\Users\olijw>conda list
# packages in environment at C:\Users\olijw\miniconda3\envs\straditize\envs\straditize:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
blas                      1.0                         mkl
blosc                     1.20.0               ha925a31_0    conda-forge
brotli                    1.0.9                ha925a31_0    conda-forge
brotlipy                  0.7.0           py37h4ab8f01_1000    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.1           py37h26f1ce3_0    conda-forge
cftime                    1.2.1            py37h44b1f71_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
charls                    2.1.0                h33f27b4_2    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              3.1              py37h26f1ce3_0    conda-forge
curl                      7.71.1               h4b64cdc_5    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37hfa6e2cd_0    conda-forge
dask-core                 2.25.0                     py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
docrep                    0.3.0              pyh9f0ad1d_0    conda-forge
docutils                  0.16             py37hc8dfbb8_1    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
freetype                  2.10.2               hd328e21_0    conda-forge
funcargparse              0.2.2                      py_0    conda-forge
giflib                    5.2.1                h2fa13f4_2    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       67.1                 h33f27b4_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2020.5.30        py37h92c78e3_2    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
intel-openmp              2019.4                      245
ipykernel                 5.3.4            py37h5ca1d4c_0    conda-forge
ipython                   7.18.1           py37hc6149b9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.2           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jxrlib                    1.1                  hfa6e2cd_2    conda-forge
kiwisolver                1.2.0            py37heaa310e_0    conda-forge
krb5                      1.17.1               hc04afaa_3    conda-forge
lcms2                     2.11                 he1115b7_0    conda-forge
lerc                      2.2                  ha925a31_0    conda-forge
libaec                    1.0.4                he025d50_1    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  10.0.1          default_hf44288c_1    conda-forge
libcurl                   7.71.1               h4b64cdc_5    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_105    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libzopfli                 1.0.3                ha925a31_0    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
markupsafe                1.1.1            py37h8055547_1    conda-forge
matplotlib-base           3.3.1            py37h35e8a6e_1    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py37hfa6e2cd_0    conda-forge
monotonic                 1.5                        py_0    conda-forge
netcdf4                   1.5.4           nompi_py37h71608f9_102    conda-forge
networkx                  2.5                        py_0    conda-forge
numpy                     1.19.1           py37h7cee19a_2    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openpyxl                  3.0.5                      py_0    conda-forge
openssl                   1.1.1g               he774522_1    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.1            py37h1834ac0_0    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.2.0            py37hc826c6e_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
prompt-toolkit            3.0.7                      py_0    conda-forge
psy-simple                1.2.0           py37hc8dfbb8_1001    conda-forge
psy-strat                 0.1.1                    py37_0    conda-forge
psyplot                   1.2.1            py37hc8dfbb8_2    conda-forge
psyplot-gui               1.2.4                    py37_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.8           h60c2a47_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywavelets                1.1.1            py37h44b1f71_1    conda-forge
pywin32                   227              py37hfa6e2cd_0    conda-forge
pyyaml                    5.3.1            py37h8055547_0    conda-forge
pyzmq                     19.0.2           py37h453f00a_0    conda-forge
qt                        5.12.6               hb2cf2c5_0    conda-forge
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
scikit-image              0.17.2           py37h3bbf574_1    conda-forge
scipy                     1.5.2            py37h9439919_0
setuptools                49.6.0           py37hc8dfbb8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    3.2.1                      py_0    conda-forge
sphinx_rtd_theme          0.5.0              pyh9f0ad1d_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.33.0               he774522_0    conda-forge
straditize                0.1.3                    py37_0    conda-forge
tifffile                  2020.9.3                   py_0    conda-forge
tk                        8.6.10               he774522_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37hfa6e2cd_0    conda-forge
traitlets                 5.0.3                      py_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
xarray                    0.16.0                     py_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.2                ha925a31_3    conda-forge
zfp                       0.5.5                ha925a31_1    conda-forge
zlib                      1.2.11            h62dcd97_1009    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge
</summary>
</details>

**Comment by Chilipp** [comment]
Hi @olijw! Thanks for raising the issue here and my apologies for the troubles you ran into. The issue comes from an incompatibility with the latest version of docrep and the latest release of psyplot. I am close to releasing a new release of psyplot but due to other things... :see_no_evil: Sorry.
 
Anyway, this should be easy to fix, just run

```bash
conda install -c conda-forge --override-channels docrep=0.2
```
after you ran `conda activate straditize`. There will be a new release of psyplot next week which should fix this issue.

**Comment by Chilipp** [comment]
> ps, while this is certainly annoying, it doesn't feel like the weirdest error message I've had trying to use Straditize: my old laptop (Windows 8.1) would give me a pop-up error window saying "This Windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586 or above)." Quite why Bluetooth was involved I have no idea..!

ok, this is really weird and certainly there is no bluetooth involved with straditize :sweat_smile: I can only imagine that this comes from the PyQt5 library and indeed, this seems to be a common problem. You could try the fix in https://github.com/GIS4WRF/gis4wrf/issues/103#issuecomment-575889035, maybe that helps?

**Comment by olijw** [comment]
Hi Philipp,

Thanks for getting back to me so quickly - it's great to be getting closer to using this tool! I tried your first solution (the docrep workaround) but while I installed it fine, calling 'straditize' led to a different series of warnings and errors:

<details>
(straditize) C:\Users\olijw>straditize
C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psy_simple\plugin.py:806: MatplotlibDeprecationWarning:
The validate_nseq_float function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  None, try_and_error(validate_none, validate_nseq_float(2)),
C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psy_simple\plugin.py:806: MatplotlibDeprecationWarning:
The _make_nseq_validator function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  None, try_and_error(validate_none, validate_nseq_float(2)),
C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psy_simple\plugin.py:1013: MatplotlibDeprecationWarning:
The validate_nseq_float function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  'texts.default_position': [(1., 1.), validate_nseq_float(2),
C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psy_simple\plugin.py:1013: MatplotlibDeprecationWarning:
The _make_nseq_validator function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  'texts.default_position': [(1., 1.), validate_nseq_float(2),
C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psy_simple\plugin.py:70: MatplotlibDeprecationWarning:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  return func(value)
WARNING:psyplot.warning:C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psyplot\config\rcsetup.py:527: PsyPlotWarning:
Trying to set 'plotter.simple.xtickprops' to {'major': {}, 'minor': {}} via the update method of RcParams which does not validate cleanly.
  self.update({key: val[0] for key, val in defaultParams.items()

WARNING:psyplot.warning:C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psyplot\config\rcsetup.py:527: PsyPlotWarning:
Trying to set 'plotter.simple.ytickprops' to {'major': {}, 'minor': {}} via the update method of RcParams which does not validate cleanly.
  self.update({key: val[0] for key, val in defaultParams.items()

C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psyplot\config\rcsetup.py:430: MatplotlibDeprecationWarning:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  cval = self.validate[key](val)
WARNING:psyplot.warning:C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psyplot\config\rcsetup.py:527: PsyPlotWarning:
Trying to set 'plotter.simple.xticks' to {'major': None, 'minor': None} via the update method of RcParams which does not validate cleanly.
  self.update({key: val[0] for key, val in defaultParams.items()

WARNING:psyplot.warning:C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psyplot\config\rcsetup.py:527: PsyPlotWarning:
Trying to set 'plotter.simple.yticks' to {'major': None, 'minor': None} via the update method of RcParams which does not validate cleanly.
  self.update({key: val[0] for key, val in defaultParams.items()

INFO:matplotlib.font_manager:Generating new fontManager, this may take some time...
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.
Traceback (most recent call last):
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'iopub_socket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'iopub_thread'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\olijw\miniconda3\envs\straditize\Scripts\straditize-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\straditize\__main__.py", line 180, in main
    parser.parse_known2func()
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\funcargparse\__init__.py", line 930, in parse_known2func
    return func(**kws), remainder
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\straditize\__main__.py", line 70, in start_app
    mainwindow = start_app(exec_=False, callback='', **kwargs)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psyplot_gui\__init__.py", line 226, in start_app
    mainwindow = MainWindow.run(fnames, project, engine, plot_method, name,
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psyplot_gui\main.py", line 972, in run
    mainwindow = cls(show=show)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psyplot_gui\main.py", line 144, in __init__
    self.console = ConsoleWidget(self)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\psyplot_gui\console.py", line 105, in __init__
    kernel_manager.start_kernel(show_banner=False)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\ipykernel\inprocess\manager.py", line 46, in start_kernel
    self.kernel = InProcessKernel(parent=self, session=self.session)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 72, in __init__
    super(InProcessKernel, self).__init__(**traits)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\ipykernel\ipkernel.py", line 71, in __init__
    self.shell.displayhook.pub_socket = self.iopub_socket
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 1577, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 975, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 67, in _default_iopub_socket
    return self.iopub_thread.background_socket
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 1577, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\traitlets\traitlets.py", line 975, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 59, in _default_iopub_thread
    thread = IOPubThread(self._underlying_iopub_socket)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\ipykernel\iostream.py", line 71, in __init__
    self._setup_event_pipe()
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\ipykernel\iostream.py", line 90, in _setup_event_pipe
    self._event_puller = ZMQStream(pipe_in, self.io_loop)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\zmq\eventloop\zmqstream.py", line 552, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\olijw\miniconda3\envs\straditize\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
</details>

Any thoughts?

Thanks,

Oli

**Comment by Chilipp** [comment]
Hi @olijw! Thanks again for letting me know. Might be related to https://github.com/ipython/ipykernel/issues/468, not sure, I'll have to try it for myself (usually I am not working on windows), but I can't do this before Monday, sorry

**Comment by olijw** [comment]
Not to worry, there's no real rush! Have a good weekend and I look forward
to revisiting this at some point in the coming week.

**Comment by Chilipp** [comment]
hey @olijw! Sorry for coming back to you so late! this is just to let you know that I am still working on it. For me, the GUI starts, but the help explorer does not load properly on Windows. I need to check what the issue is here. On Wednesday I should have time for it, but this has a high priority

**Comment by olijw** [comment]
Hi @chillip, thanks for continuing to work on this! I hope you’ve been making headway with it all, and I really look forward to being able to try out the program when it’s all working as it should :) From: Philipp S. SommerSent: 13 September 2020 20:52To: Chilipp/straditizeCc: olijw; MentionSubject: Re: [Chilipp/straditize] Straditize fails to launch (#19) hey @olijw! Sorry for coming back to you so late! this is just to let you know that I am still working on it. For me, the GUI starts, but the help explorer does not load properly on Windows. I need to check what the issue is here. On Wednesday I should have time for it, but this has a high priority—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Chilipp** [comment]
Hi @olijw, the installation should work now via `conda create -n straditize -c psyplot/label/master -c conda-forge straditize` . Could you try this please? My apologies for the delay.

**Comment by olijw** [comment]
Hi Philipp, this does indeed work! Thanks very much for your hard work sorting it out, and for putting together such a great tool - I'm already enjoying working out how to use it!
All the best,
Oli
