### ISSUE TITLE
Straditize Fail to launch on Windows & convert image all black

### ISSUE THREAD

**Issue by zhouborui97** [Chilipp/straditize#21]
Dear Sir, 
I'm writing to inquiry about the project Stratidize you published on Github.
I am a graduate student from China, and I study in the field of paleoecology and pollen analysis. I have been using your marvelous python package Straditize for a year, but some problem have haunted me for a long time. Therefore, I would be grateful to discuss it with you.
The first problem is: I download Straditize 0.1.3 in November 2020, and the package is still functional. But all the package installed afterwards had a same problem in every computer( WINDOWS version). After I "select data part" and pressed "convert image", the image of the selected part blacked out totally. Then I tried to "digitize", and the curve of the diagram could still be found and marked by Straditze, but the data part was still total black (which can be seen in the appendix of this e-mail). However, the package installed the earliest is still working properly.
The second problem is the major one : when I used other computers to install Straditize by running "conda create -n straditize -c conda-forge straditize", it didn't work. Because I not really familiar with Python, I would really appreciate your help.

Yours sincerely.

Zhou

More information below about the second problem.

<details>
<summary>psyplot -aV</summary>

(straditize) C:\Users\A>psyplot -aV
WARNING:psyplot.config.rcsetup:Failed to import plugin = psy_simple.plugin!
WARNING:psyplot.config.rcsetup:Failed to import plugin = psy_strat.plugin!
WARNING:psyplot:Could not import plugin = psy_simple.plugin
Traceback (most recent call last):
  File "C:\Users\A\anaconda3\envs\straditize\Scripts\psyplot-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\A\anaconda3\envs\straditize\lib\site-packages\psyplot\__main__.py", line 73, in main
    parser.parse_known2func(args)
  File "C:\Users\A\anaconda3\envs\straditize\lib\site-packages\funcargparse\__init__.py", line 956, in parse_known2func
    ns, remainder = self.parse_known_args(args)
  File "C:\Users\A\anaconda3\envs\straditize\lib\site-packages\funcargparse\__init__.py", line 746, in parse_known_args
    return super(FuncArgParser, self).parse_known_args(args, namespace)
  File "C:\Users\A\anaconda3\envs\straditize\lib\argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\A\anaconda3\envs\straditize\lib\argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\A\anaconda3\envs\straditize\lib\argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "C:\Users\A\anaconda3\envs\straditize\lib\argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\A\anaconda3\envs\straditize\lib\site-packages\psyplot\__main__.py", line 364, in __call__
    print(yaml.dump(psyplot.get_versions(), default_flow_style=False))
  File "C:\Users\A\anaconda3\envs\straditize\lib\site-packages\psyplot\__init__.py", line 139, in get_versions
    ret[str(ep.module_name)] = mod.get_versions(requirements)
UnboundLocalError: local variable 'mod' referenced before assignment

</details>

<details>
<summary>straditize -V</summary>

(straditize) C:\Users\A>straditize -V
WARNING:psyplot.config.rcsetup:Failed to import plugin = psy_simple.plugin!
WARNING:psyplot.config.rcsetup:Failed to import plugin = psy_strat.plugin!
0.1.3

</details>

<details>
<summary>conda info -a</summary>

```
# (straditize) C:\Users\A>conda info -a

     active environment : straditize
    active env location : C:\Users\A\anaconda3\envs\straditize
            shell level : 2
       user config file : C:\Users\A\.condarc
 populated config files : C:\Users\A\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __cuda=9.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\A\anaconda3  (writable)
      conda av data dir : C:\Users\A\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\A\anaconda3\pkgs
                          C:\Users\A\.conda\pkgs
                          C:\Users\A\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\A\anaconda3\envs
                          C:\Users\A\.conda\envs
                          C:\Users\A\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

# conda environments:
#
base                     C:\Users\A\anaconda3
straditize            *  C:\Users\A\anaconda3\envs\straditize

sys.version: 3.9.7 (default, Sep 16 2021, 16:59:28) [...
sys.prefix: C:\Users\A\anaconda3
sys.executable: C:\Users\A\anaconda3\python.exe
conda location: C:\Users\A\anaconda3\lib\site-packages\conda
conda-build: C:\Users\A\anaconda3\Scripts\conda-build.exe
conda-content-trust: C:\Users\A\anaconda3\Scripts\conda-content-trust.exe
conda-convert: C:\Users\A\anaconda3\Scripts\conda-convert.exe
conda-debug: C:\Users\A\anaconda3\Scripts\conda-debug.exe
conda-develop: C:\Users\A\anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\A\anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\A\anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\A\anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\A\anaconda3\Scripts\conda-metapackage.exe
conda-pack: C:\Users\A\anaconda3\Scripts\conda-pack.exe
conda-render: C:\Users\A\anaconda3\Scripts\conda-render.exe
conda-repo: C:\Users\A\anaconda3\Scripts\conda-repo.exe
conda-server: C:\Users\A\anaconda3\Scripts\conda-server.exe
conda-skeleton: C:\Users\A\anaconda3\Scripts\conda-skeleton.exe
conda-token: C:\Users\A\anaconda3\Scripts\conda-token.exe
conda-verify: C:\Users\A\anaconda3\Scripts\conda-verify.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: straditize
CONDA_EXE: C:\Users\A\anaconda3\condabin\..\Scripts\conda.exe
CONDA_EXES: "C:\Users\A\anaconda3\condabin\..\Scripts\conda.exe"
CONDA_PREFIX: C:\Users\A\anaconda3\envs\straditize
CONDA_PREFIX_1: C:\Users\A\anaconda3
CONDA_PROMPT_MODIFIER: (straditize)
CONDA_PYTHON_EXE: C:\Users\A\anaconda3\python.exe
CONDA_ROOT: C:\Users\A\anaconda3
CONDA_SHLVL: 2
CURL_CA_BUNDLE: <not set>
HOMEPATH: \Users\A
PATH: C:\Users\A\anaconda3;C:\Users\A\anaconda3\Library\mingw-w64\bin;C:\Users\A\anaconda3\Library\usr\bin;C:\Users\A\anaconda3\Library\bin;C:\Users\A\anaconda3\Scripts;C:\Users\A\anaconda3\bin;C:\Users\A\anaconda3\envs\straditize;C:\Users\A\anaconda3\envs\straditize\Library\mingw-w64\bin;C:\Users\A\anaconda3\envs\straditize\Library\usr\bin;C:\Users\A\anaconda3\envs\straditize\Library\bin;C:\Users\A\anaconda3\envs\straditize\Scripts;C:\Users\A\anaconda3\envs\straditize\bin;C:\Users\A\anaconda3\condabin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Users\A\AppData\Local\Microsoft\WindowsApps;.
PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
QT_QPA_PLATFORM_PLUGIN_PATH: C:\Users\A\anaconda3\envs\straditize\Library\plugins
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
```
</details>

<details>
<summary>conda list</summary>

```
# (straditize) C:\Users\A>conda list
# packages in environment at C:\Users\A\anaconda3\envs\straditize:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
brotlipy                  0.7.0           py38h294d835_1003    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.0.4                h09319c2_1    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py38haa244fe_1    conda-forge
cffi                      1.15.0           py38hd8c33c5_0    conda-forge
cfitsio                   4.0.0                hd67004f_0    conda-forge
cftime                    1.5.1.1          py38h6f4d8f0_1    conda-forge
charls                    2.2.0                h39d44d4_0    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              36.0.1           py38hb7941b4_0    conda-forge
curl                      7.80.0               h789b8ee_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py38h294d835_1    conda-forge
dask-core                 2021.12.0          pyhd8ed1ab_0    conda-forge
debugpy                   1.5.1            py38h885f38d_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
docrep                    0.3.2              pyh44b312d_0    conda-forge
docutils                  0.15.2           py38haa244fe_3    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
fasteners                 0.16               pyhd8ed1ab_0    conda-forge
fonttools                 4.28.5           py38h294d835_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
fsspec                    2021.11.1          pyhd8ed1ab_0    conda-forge
funcargparse              0.2.5              pyhd8ed1ab_0    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_103    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagecodecs               2021.11.20       py38h84a8deb_1    conda-forge
imageio                   2.13.5             pyh239f2a4_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.10.0           py38haa244fe_0    conda-forge
importlib_metadata        4.10.0               hd8ed1ab_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
ipykernel                 6.6.1            py38h595d716_0    conda-forge
ipython                   7.30.1           py38haa244fe_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.1           py38haa244fe_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38haa244fe_1    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kiwisolver                1.3.2            py38hbd9d945_1    conda-forge
krb5                      1.19.2               h20d022d_3    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.80.0               h789b8ee_1    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.0.1            py38h294d835_1    conda-forge
matplotlib                3.5.1            py38haa244fe_0    conda-forge
matplotlib-base           3.5.1            py38h1f000d6_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
monotonic                 1.5                        py_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.8           nompi_py38h0500770_101    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
numpy                     1.22.0           py38hcf66579_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py38h5d928e2_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py38h794f750_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
psy-simple                1.3.1+5.gac305c0            py38    psyplot/label/master
psy-strat                 0.1.1                    py38_0    conda-forge
psyplot                   1.3.1+14.gfcd5883            py38    psyplot/label/master
psyplot-gui               1.3.0+11.g227d84e            py38    psyplot/label/master
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38haa244fe_8    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_8    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_8    conda-forge
pyqtchart                 5.12             py38h885f38d_8    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_8    conda-forge
pysocks                   1.7.1            py38haa244fe_4    conda-forge
python                    3.8.12          h7840368_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.2.0            py38h6f4d8f0_1    conda-forge
pywin32                   303              py38h294d835_0    conda-forge
pyyaml                    6.0              py38h294d835_3    conda-forge
pyzmq                     22.3.0           py38h09162b1_1    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtconsole                 5.2.2              pyhd8ed1ab_1    conda-forge
qtconsole-base            5.2.2              pyhd8ed1ab_1    conda-forge
qtpy                      2.0.0              pyhd8ed1ab_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
scikit-image              0.19.1           py38h5d928e2_0    conda-forge
scipy                     1.7.3            py38ha1292f7_0    conda-forge
setuptools                60.2.0           py38haa244fe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.3.2              pyh6c4a22f_0    conda-forge
sphinx_rtd_theme          1.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_1    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
straditize                0.1.3                    py38_0    conda-forge
tbb                       2021.5.0             h2d74725_0    conda-forge
tifffile                  2021.11.2          pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h294d835_2    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py38h294d835_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_3    conda-forge
xarray                    0.20.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zfp                       0.5.5                h0e60522_8    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.1                h6255e5f_0    conda-forge
```
</details>

**Comment by Freebilbil** [comment]
This problem has also confused me.
I have tried codes as follow: conda create -n straditize -c psyplot/label/master -c conda-forge straditize;
                                                conda create -n straditize -c conda-forge straditize
but both of codes have the same error:
WARNING:psyplot.config.rcsetup:Failed to import plugin = psy_simple.plugin!
WARNING:psyplot.config.rcsetup:Failed to import plugin = psy_strat.plugin!
WARNING:psyplot:Could not import plugin = psy_simple.plugin

I really have no idea ..
@Chilipp plz..

**Comment by Chilipp** [comment]
dear @Freebilbil! I feel sorry that you ran into these issues. Unfortunately I could not spend resources on maintaining the straditize library which is why you are facing these issues. They are just not up-to-date with the latest libraries...

I do not yet know when I will be able to make a new release of straditize as there are a few more things to fix, but the problems you mention here should hopefully be resolved by the changes in #22. Can you please try the following?

```bash
conda activate straditize
pip install git+https://github.com/Chilipp/straditize.git@fix/black-image
```

to solve the second issue, you should use matplotlib 3.4, i.e.

```bash
conda install matplotlib==3.4
```

which hopefully resolves the issue.

**Comment by Freebilbil** [comment]
Thank you very much for your reply！
I have tried this ,but it doesn't work. And have new errors(in my MacBook):
Collecting git+https://github.com/Chilipp/straditize.git@fix/black-image
  Cloning https://github.com/Chilipp/straditize.git (to revision fix/black-image) to /private/var/folders/gr/3b5jcvq926l2xc7jt3z4hj980000gn/T/pip-req-build-kr4exwr7
  Running command git clone --filter=blob:none -q https://github.com/Chilipp/straditize.git /private/var/folders/gr/3b5jcvq926l2xc7jt3z4hj980000gn/T/pip-req-build-kr4exwr7
  fatal: unable to access 'https://github.com/Chilipp/straditize.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

WARNING: Discarding git+https://github.com/Chilipp/straditize.git@fix/black-image. Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/Chilipp/straditize.git /private/var/folders/gr/3b5jcvq926l2xc7jt3z4hj980000gn/T/pip-req-build-kr4exwr7 Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/Chilipp/straditize.git /private/var/folders/gr/3b5jcvq926l2xc7jt3z4hj980000gn/T/pip-req-build-kr4exwr7 Check the logs for full command output.

**Comment by Freebilbil** [comment]
Thank you very much for your reply！@Chilipp
I have tried this ,but it doesn't work. And have new errors(in my MacBook):
Collecting git+https://github.com/Chilipp/straditize.git@fix/black-image
Cloning https://github.com/Chilipp/straditize.git (to revision fix/black-image) to /private/var/folders/gr/3b5jcvq926l2xc7jt3z4hj980000gn/T/pip-req-build-kr4exwr7
Running command git clone --filter=blob:none -q https://github.com/Chilipp/straditize.git /private/var/folders/gr/3b5jcvq926l2xc7jt3z4hj980000gn/T/pip-req-build-kr4exwr7
fatal: unable to access 'https://github.com/Chilipp/straditize.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

WARNING: Discarding git+https://github.com/Chilipp/straditize.git@fix/black-image. Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/Chilipp/straditize.git /private/var/folders/gr/3b5jcvq926l2xc7jt3z4hj980000gn/T/pip-req-build-kr4exwr7 Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/Chilipp/straditize.git /private/var/folders/gr/3b5jcvq926l2xc7jt3z4hj980000gn/T/pip-req-build-kr4exwr7 Check the logs for full command output.

**Comment by Chilipp** [comment]
> fatal: unable to access 'https://github.com/Chilipp/straditize.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

sounds to me like your having issue with reaching out to the internet from the corresponding device, do you @Freebilbil? Otherwise you can also try to do it manually, e.g. via

```bash
conda activate straditize
git clone https://github.com/Chilipp/straditize
cd straditize
git checkout fix/black-image
pip install .
```

**Comment by zhouborui97** [comment]
I'm sorry. I am not quite understand. the"fix/black-image"solution is for the"convert image all black" problem and the matplotlib3.4 is for the "fail to launch" problem?

**Comment by Chilipp** [comment]
> the"fix/black-image"solution is for the"convert image all black" problem and the matplotlib3.4 is for the "fail to launch" problem?

yes indeed @zhouborui97

**Comment by zhouborui97** [comment]
ok i will check.

**Comment by Freebilbil** [comment]
@Chilipp sry,I run the wrong code to install straditize
now I input: conda install matplotlib==3.4

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - matplotlib==3.4

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


I am not sure.Is this still a network problem？

**Comment by zhouborui97** [comment]
thanks a lot, the matplotlib 3.4 did solve the launching problem. i will continue to work on the convert image black problem @Chilipp

**Comment by Chilipp** [comment]
my apologies @Freebilbil, it was a typo. You need to use `conda install matplotlib=3.4` not `conda install matplotlib==3.4`

**Comment by zhouborui97** [comment]
ues " pip install matplotlib==3.4.3" after using "pip uninstall matplotlib" to uninstall the 3.5 version of matplotlib @Freebilbil

**Comment by zhouborui97** [comment]
after gei image-black from github and run "pip install .", this error comes out

Processing c:\users\a\straditize
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\A\anaconda3\envs\straditize\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A\\straditize\\setup.py'"'"'; __file__='"'"'C:\\Users\\A\\straditize\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\A\AppData\Local\Temp\pip-pip-egg-info-l_uzs8q0'
       cwd: C:\Users\A\straditize\
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\A\straditize\setup.py", line 59, in <module>
      long_description=readme(),
    File "C:\Users\A\straditize\setup.py", line 25, in readme
      return f.read()
  UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 2639: illegal multibyte sequence
  ----------------------------------------
WARNING: Discarding file:///C:/Users/A/straditize. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Chilipp** [comment]
hmm ok. this is weird. Maybe you just uncomment line 59 in the `setup.py` file. no idea why this is causing problems...

**Comment by zhouborui97** [comment]
yeah, after i delect that line, it finally work. No more black image! thanks a lot! Appreciate the help!

**Comment by Chilipp** [comment]
you're welcome! and my apologies again for the issues. that's the problem with open-source software in research. too hard to maintain if the developer changes the job :disappointed: although I will try to put this repository here in a better condition

**Comment by chmzs** [comment]
> yeah, after i delect that line, it finally work. No more black image! thanks a lot! Appreciate the help!

Could you please share the environment.yml?
