### ISSUE TITLE
Fail to import image

### ISSUE THREAD

**Issue by HAOYANWANG000** [Chilipp/straditize#23]
**Hi Chilipp, It's a nice weekend, but I meet a problem in STRADITIZE when I try to import a image (xx.jpg).
Hope you can help me, my thanks!

Here is the error code?**

'PsyplotCanvasManager' object has no attribute '_get_toolbar' 
Traceback (most recent call last):
File "E:\pytho\envs\straditize\lib\site-packages\straditize\widgets\menu_actions.py", line 430, in import_full_image
self.open_straditizer(image)
File "E:\pytho\envs\straditize\lib\site-packages\straditize\widgets\menu_actions.py", line 535, in open_straditizer
stradi = Straditizer(fname, *args, **kwargs)
File "E:\pytho\envs\straditize\lib\site-packages\straditize\straditizer.py", line 368, in __init__
self.plot_image()
File "E:\pytho\envs\straditize\lib\site-packages\straditize\straditizer.py", line 410, in plot_image
fig = plt.figure()
File "E:\pytho\envs\straditize\lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
return func(*args, **kwargs)
File "E:\pytho\envs\straditize\lib\site-packages\matplotlib\pyplot.py", line 840, in figure
manager = new_figure_manager(
File "E:\pytho\envs\straditize\lib\site-packages\matplotlib\pyplot.py", line 384, in new_figure_manager
return _get_backend_mod().new_figure_manager(*args, **kwargs)
File "E:\pytho\envs\straditize\lib\site-packages\psyplot_gui\backend.py", line 74, in new_figure_manager
return new_figure_manager_given_figure(num, thisFig)
File "E:\pytho\envs\straditize\lib\site-packages\psyplot_gui\backend.py", line 82, in new_figure_manager_given_figure
return PsyplotCanvasManager(canvas, num)
File "E:\pytho\envs\straditize\lib\site-packages\psyplot_gui\backend.py", line 109, in __init__
self.toolbar = self._get_toolbar(canvas, parent_widget)
AttributeError: 'PsyplotCanvasManager' object has no attribute '_get_toolbar'

**Comment by Chilipp** [comment]
@HAOYANWANG000 my apologies for the issues you face. in fact, I did not have any resources to work or maintain straditize in the past couple of years (as you see, that last commit to this repo was 5 years ago). So I do not recommend to use `straditize` as it is not up-to-date with the latest libraries until someone from the community volunteers to work on it.

**Comment by HAOYANWANG000** [comment]
OMG!!!!!!?? That's a sad news.
STRADITIZE is still very useful in areas where some of the research data is not open-sourced.

Retreat the Matlab version could address current issues.
conda install matplotlib=3.4

**Comment by Chilipp** [comment]
I know, sorry :cry: but at some point I have to face the fact that I will not have the resources to work on this as my job now differs a lot from working to paleoclimatological sample data.
